
abstract=
ontologyTitle=
ontologyPrefix=vivo
ontologyNamespaceURI=http://vivoweb.org/ontology/core
ontologyName=VIVO Core Ontology
thisVersionURI=null
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=1.9.0-SNAPSHOT
licenseURI=https://spdx.org/licenses/Unlicense.html
licenseName=https://spdx.org/licenses/Unlicense.html
licenseIconURL=null
citeAs=VIVO Ontology Interest Group. Revision: 1.9.0-SNAPSHOT.
DOI=
status=Ontology Specification Draft
logo=
description=The VIVO Ontology is used to represent the expertise of people engaged in the creation, transmission, and preservation of knowledge and creative works. The VIVO ontology (hereafter referred to as “the ontology”) represents expertise by describing the activities and accomplishments of people in terms of their relationships to particular artifacts of the work, resources they use, institutions that employ them, and other indicators. The ontology is independent of knowledge or creative domain. The ontology supports the identification, evaluation, and impact assessment of individual people and groups of people, as well as identification and reuse of the works of the people.
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=VIVO Ontology Interest Group
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
