name: Setup Apache Jena

on: [push, pull_request]

jobs:
  setup-jena:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Apache Jena
        run: |
          curl -sS --fail "https://dlcdn.apache.org/jena/binaries/apache-jena-5.1.0.tar.gz" -o "/home/runner/work/_temp/apache-jena-5.1.0.tar.gz"

      - name: Extract Apache Jena
        run: |
          tar -xzf /home/runner/work/_temp/apache-jena-5.1.0.tar.gz -C /home/runner/work/_temp/

      - name: List extracted files
        run: ls -la /home/runner/work/_temp/

      - name: Set up environment variables
        run: |
          echo "JENA_HOME=/home/runner/work/_temp/apache-jena-fuseki-5.1.0" >> $GITHUB_ENV
          echo "$JENA_HOME/bin" >> $GITHUB_PATH

      - name: Verify Jena setup
        run: |
          echo "Jena version:"
          $JENA_HOME/bin/jena --version
