name: RDF Syntax Check

on: [push, pull_request]

jobs:
  rdf-syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: RDF syntax check
        uses: AtomGraph/RDF-syntax-check@v1.0.5
        with:
          # The Jena version to set up; pin to a specific version if needed
          jena-version: '4.7.0'  # Default value, adjust as necessary
          
          # The Apache distribution URL; use the default if no custom URL is needed
          asf-archive: 'https://archive.apache.org/dist/apache-jena/'
          
          # Optionally, specify additional configurations here if the action supports it
