name: RDF Syntax Check

on: [push, pull_request]

jobs:
  rdf-syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Apache Jena
        run: |
          curl -sS --fail "https://dlcdn.apache.org/jena/binaries/apache-jena-5.1.0.tar.gz" -o "/home/runner/work/_temp/jena.tar.gz"

      - name: Extract Apache Jena
        run: |
          tar -xzf /home/runner/work/_temp/jena.tar.gz -C /home/runner/work/_temp/
        
      - name: RDF syntax check
        uses: AtomGraph/RDF-syntax-check@v1.0.5
        with:
          jena-version: '5.1.0'
          asf-archive: 'https://dlcdn.apache.org/jena/binaries/'
