name: RDF Syntax Check

on: [push, pull_request]

jobs:
  rdf-syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Apache Jena
        run: |
          curl -sS --fail "https://archive.apache.org/dist/apache-jena/binaries/apache-jena-4.7.0-bin.tar.gz" -o "/home/runner/work/_temp/jena-bin.tar.gz"
        continue-on-error: true

      - name: Extract Apache Jena
        run: |
          tar -xzf /home/runner/work/_temp/jena-bin.tar.gz -C /home/runner/work/_temp/
        
      - name: RDF syntax check
        uses: AtomGraph/RDF-syntax-check@v1.0.5
        with:
          jena-version: '4.7.0'
          asf-archive: 'https://archive.apache.org/dist/apache-jena/binaries/'
