name: Validate vivo.owl

on:
  pull_request:
    paths:
      - 'vivo.owl'  # trigger if  vivo.owl is changed
  workflow_dispatch: # manual trigger
jobs:
  validate-rdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Apache Jena
        run: |
          wget https://downloads.apache.org/jena/binaries/apache-jena-4.8.0.tar.gz -O apache-jena.tar.gz
          ls -la apache-jena.tar.gz

      - name: Extract Apache Jena
        run: |
          tar -xzf apache-jena.tar.gz
          ls -la apache-jena-4.8.0/bin

      - name: Add Apache Jena to PATH
        run: |
          export PATH=$GITHUB_WORKSPACE/apache-jena-4.8.0/bin:$PATH
          echo "Updated PATH: $PATH"

      - name: Validate RDF
        run: |
          $GITHUB_WORKSPACE/apache-jena-4.8.0/bin/riot --validate vivo.owl > validation_report.txt || true
          cat validation_report.txt

      # Validate vivo.owl with Apache Jena's riot
      - name: Validate vivo.owl
        id: validate
        run: |
          riot --validate vivo.owl > validation_report.txt || true

      # Output validation report as a PR comment
      - name: Post validation report to PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Validation Report for vivo.owl
          path: validation_report.txt
